In [1]:
import numpy as np

In [4]:
xy=np.load("xy.npy")

In [14]:
xy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
xz=np.arange(100,500,2.5,dtype="float64")

In [16]:
xz

array([100. , 102.5, 105. , 107.5, 110. , 112.5, 115. , 117.5, 120. ,
       122.5, 125. , 127.5, 130. , 132.5, 135. , 137.5, 140. , 142.5,
       145. , 147.5, 150. , 152.5, 155. , 157.5, 160. , 162.5, 165. ,
       167.5, 170. , 172.5, 175. , 177.5, 180. , 182.5, 185. , 187.5,
       190. , 192.5, 195. , 197.5, 200. , 202.5, 205. , 207.5, 210. ,
       212.5, 215. , 217.5, 220. , 222.5, 225. , 227.5, 230. , 232.5,
       235. , 237.5, 240. , 242.5, 245. , 247.5, 250. , 252.5, 255. ,
       257.5, 260. , 262.5, 265. , 267.5, 270. , 272.5, 275. , 277.5,
       280. , 282.5, 285. , 287.5, 290. , 292.5, 295. , 297.5, 300. ,
       302.5, 305. , 307.5, 310. , 312.5, 315. , 317.5, 320. , 322.5,
       325. , 327.5, 330. , 332.5, 335. , 337.5, 340. , 342.5, 345. ,
       347.5, 350. , 352.5, 355. , 357.5, 360. , 362.5, 365. , 367.5,
       370. , 372.5, 375. , 377.5, 380. , 382.5, 385. , 387.5, 390. ,
       392.5, 395. , 397.5, 400. , 402.5, 405. , 407.5, 410. , 412.5,
       415. , 417.5,

In [22]:
xz.sum(axis=0)

47800.0

In [23]:
xz.size

160

In [24]:
xz.resize(10,16)

In [25]:
xz

array([[100. , 102.5, 105. , 107.5, 110. , 112.5, 115. , 117.5, 120. ,
        122.5, 125. , 127.5, 130. , 132.5, 135. , 137.5],
       [140. , 142.5, 145. , 147.5, 150. , 152.5, 155. , 157.5, 160. ,
        162.5, 165. , 167.5, 170. , 172.5, 175. , 177.5],
       [180. , 182.5, 185. , 187.5, 190. , 192.5, 195. , 197.5, 200. ,
        202.5, 205. , 207.5, 210. , 212.5, 215. , 217.5],
       [220. , 222.5, 225. , 227.5, 230. , 232.5, 235. , 237.5, 240. ,
        242.5, 245. , 247.5, 250. , 252.5, 255. , 257.5],
       [260. , 262.5, 265. , 267.5, 270. , 272.5, 275. , 277.5, 280. ,
        282.5, 285. , 287.5, 290. , 292.5, 295. , 297.5],
       [300. , 302.5, 305. , 307.5, 310. , 312.5, 315. , 317.5, 320. ,
        322.5, 325. , 327.5, 330. , 332.5, 335. , 337.5],
       [340. , 342.5, 345. , 347.5, 350. , 352.5, 355. , 357.5, 360. ,
        362.5, 365. , 367.5, 370. , 372.5, 375. , 377.5],
       [380. , 382.5, 385. , 387.5, 390. , 392.5, 395. , 397.5, 400. ,
        402.5, 405. , 407.

In [26]:
xz.transpose()

array([[100. , 140. , 180. , 220. , 260. , 300. , 340. , 380. , 420. ,
        460. ],
       [102.5, 142.5, 182.5, 222.5, 262.5, 302.5, 342.5, 382.5, 422.5,
        462.5],
       [105. , 145. , 185. , 225. , 265. , 305. , 345. , 385. , 425. ,
        465. ],
       [107.5, 147.5, 187.5, 227.5, 267.5, 307.5, 347.5, 387.5, 427.5,
        467.5],
       [110. , 150. , 190. , 230. , 270. , 310. , 350. , 390. , 430. ,
        470. ],
       [112.5, 152.5, 192.5, 232.5, 272.5, 312.5, 352.5, 392.5, 432.5,
        472.5],
       [115. , 155. , 195. , 235. , 275. , 315. , 355. , 395. , 435. ,
        475. ],
       [117.5, 157.5, 197.5, 237.5, 277.5, 317.5, 357.5, 397.5, 437.5,
        477.5],
       [120. , 160. , 200. , 240. , 280. , 320. , 360. , 400. , 440. ,
        480. ],
       [122.5, 162.5, 202.5, 242.5, 282.5, 322.5, 362.5, 402.5, 442.5,
        482.5],
       [125. , 165. , 205. , 245. , 285. , 325. , 365. , 405. , 445. ,
        485. ],
       [127.5, 167.5, 207.5, 247.5, 287.5, 

In [27]:
xz.flatten()

array([100. , 102.5, 105. , 107.5, 110. , 112.5, 115. , 117.5, 120. ,
       122.5, 125. , 127.5, 130. , 132.5, 135. , 137.5, 140. , 142.5,
       145. , 147.5, 150. , 152.5, 155. , 157.5, 160. , 162.5, 165. ,
       167.5, 170. , 172.5, 175. , 177.5, 180. , 182.5, 185. , 187.5,
       190. , 192.5, 195. , 197.5, 200. , 202.5, 205. , 207.5, 210. ,
       212.5, 215. , 217.5, 220. , 222.5, 225. , 227.5, 230. , 232.5,
       235. , 237.5, 240. , 242.5, 245. , 247.5, 250. , 252.5, 255. ,
       257.5, 260. , 262.5, 265. , 267.5, 270. , 272.5, 275. , 277.5,
       280. , 282.5, 285. , 287.5, 290. , 292.5, 295. , 297.5, 300. ,
       302.5, 305. , 307.5, 310. , 312.5, 315. , 317.5, 320. , 322.5,
       325. , 327.5, 330. , 332.5, 335. , 337.5, 340. , 342.5, 345. ,
       347.5, 350. , 352.5, 355. , 357.5, 360. , 362.5, 365. , 367.5,
       370. , 372.5, 375. , 377.5, 380. , 382.5, 385. , 387.5, 390. ,
       392.5, 395. , 397.5, 400. , 402.5, 405. , 407.5, 410. , 412.5,
       415. , 417.5,

In [30]:
xz.transpose()

array([[100. , 140. , 180. , 220. , 260. , 300. , 340. , 380. , 420. ,
        460. ],
       [102.5, 142.5, 182.5, 222.5, 262.5, 302.5, 342.5, 382.5, 422.5,
        462.5],
       [105. , 145. , 185. , 225. , 265. , 305. , 345. , 385. , 425. ,
        465. ],
       [107.5, 147.5, 187.5, 227.5, 267.5, 307.5, 347.5, 387.5, 427.5,
        467.5],
       [110. , 150. , 190. , 230. , 270. , 310. , 350. , 390. , 430. ,
        470. ],
       [112.5, 152.5, 192.5, 232.5, 272.5, 312.5, 352.5, 392.5, 432.5,
        472.5],
       [115. , 155. , 195. , 235. , 275. , 315. , 355. , 395. , 435. ,
        475. ],
       [117.5, 157.5, 197.5, 237.5, 277.5, 317.5, 357.5, 397.5, 437.5,
        477.5],
       [120. , 160. , 200. , 240. , 280. , 320. , 360. , 400. , 440. ,
        480. ],
       [122.5, 162.5, 202.5, 242.5, 282.5, 322.5, 362.5, 402.5, 442.5,
        482.5],
       [125. , 165. , 205. , 245. , 285. , 325. , 365. , 405. , 445. ,
        485. ],
       [127.5, 167.5, 207.5, 247.5, 287.5, 

In [31]:
xz

array([[100. , 102.5, 105. , 107.5, 110. , 112.5, 115. , 117.5, 120. ,
        122.5, 125. , 127.5, 130. , 132.5, 135. , 137.5],
       [140. , 142.5, 145. , 147.5, 150. , 152.5, 155. , 157.5, 160. ,
        162.5, 165. , 167.5, 170. , 172.5, 175. , 177.5],
       [180. , 182.5, 185. , 187.5, 190. , 192.5, 195. , 197.5, 200. ,
        202.5, 205. , 207.5, 210. , 212.5, 215. , 217.5],
       [220. , 222.5, 225. , 227.5, 230. , 232.5, 235. , 237.5, 240. ,
        242.5, 245. , 247.5, 250. , 252.5, 255. , 257.5],
       [260. , 262.5, 265. , 267.5, 270. , 272.5, 275. , 277.5, 280. ,
        282.5, 285. , 287.5, 290. , 292.5, 295. , 297.5],
       [300. , 302.5, 305. , 307.5, 310. , 312.5, 315. , 317.5, 320. ,
        322.5, 325. , 327.5, 330. , 332.5, 335. , 337.5],
       [340. , 342.5, 345. , 347.5, 350. , 352.5, 355. , 357.5, 360. ,
        362.5, 365. , 367.5, 370. , 372.5, 375. , 377.5],
       [380. , 382.5, 385. , 387.5, 390. , 392.5, 395. , 397.5, 400. ,
        402.5, 405. , 407.

In [37]:
np.split(xz,[[.5]])

TypeError: slice indices must be integers or None or have an __index__ method