In [1]:
import numpy as np

In [20]:
arr=np.array([[1,2,3,4,5],[4,2,3,4,5]],dtype=float,ndmin=3)
np.ndim(arr)

3

In [26]:
arr.shape

(1, 2, 5)

In [33]:
arr.reshape(5,2)

array([[1., 2.],
       [3., 4.],
       [5., 4.],
       [2., 3.],
       [4., 5.]])

In [34]:
ass=np.arange(24)

In [36]:
ass.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
ass.reshape(1,24)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [39]:
ass.reshape(1,2,12)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]])

In [40]:
ass.reshape(1,2,6,2)

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]]])

In [41]:
ass.itemsize

4

In [43]:
ass.flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [54]:
zero=np.ones([3,2,2],dtype="int32",order='C')

In [55]:
zero

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [65]:
xz=zero.ravel()

In [66]:
xz

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [67]:
np.save('xy',xz)

In [70]:
np.load('xy.npy')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [73]:
Narray=np.arange(10,100,2,dtype="int32")

In [74]:
Narray

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [75]:
Narray.shape

(45,)

In [77]:
Marray=np.arange(11,100,2)

In [78]:
Marray

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77,
       79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [79]:
Marray.shape

(45,)

In [86]:
same=np.intersect1d(Narray,Marray)

In [87]:
same

array([], dtype=int32)

In [89]:
different=np.setdiff1d(Narray,Marray)

In [90]:
different

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])