# Label Encoding

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [29]:
df=pd.read_csv('carprices.csv')

In [30]:
df

Car  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [31]:
LE=LabelEncoder()

In [32]:
df_encoded=df

In [38]:
df_encoded.Car=LE.fit_transform(df_encoded.Car)

In [39]:
df_encoded

Car  Mileage  Sell Price($)  Age(yrs)
0     1    69000          18000         6
1     1    35000          34000         3
2     1    57000          26100         5
3     1    22500          40000         2
4     1    46000          31500         4
5     0    59000          29400         5
6     0    52000          32000         5
7     0    72000          19300         6
8     0    91000          12000         8
9     2    67000          22000         6
10    2    83000          20000         7
11    2    79000          21000         7
12    2    59000          33000         5

In [46]:
X = df_encoded[['Car','Mileage']].values

In [47]:
X

array([[    1, 69000],
       [    1, 35000],
       [    1, 57000],
       [    1, 22500],
       [    1, 46000],
       [    0, 59000],
       [    0, 52000],
       [    0, 72000],
       [    0, 91000],
       [    2, 67000],
       [    2, 83000],
       [    2, 79000],
       [    2, 59000]], dtype=int64)

In [56]:
df_encoded

Car  Mileage  Sell Price($)  Age(yrs)
0     1    69000          18000         6
1     1    35000          34000         3
2     1    57000          26100         5
3     1    22500          40000         2
4     1    46000          31500         4
5     0    59000          29400         5
6     0    52000          32000         5
7     0    72000          19300         6
8     0    91000          12000         8
9     2    67000          22000         6
10    2    83000          20000         7
11    2    79000          21000         7
12    2    59000          33000         5

# Linear Model Train

In [57]:
from sklearn.linear_model import LinearRegression

In [58]:
lr=LinearRegression()

In [62]:
x=df_encoded[['Car','Mileage','Age(yrs)']]

In [63]:
y=df_encoded[['Sell Price($)']]

In [64]:
lr.fit(x,y)

LinearRegression()

In [65]:
y_pred=lr.predict(x)

In [66]:
y_pred

array([[22855.47176747],
       [36101.34690856],
       [27545.28569062],
       [40997.05248879],
       [31823.31629959],
       [25620.04649333],
       [28502.52969256],
       [20518.449256  ],
       [13197.73798059],
       [24780.71096476],
       [18443.76378491],
       [20090.89704162],
       [27823.3916312 ]])

# 1) Predict price of a mercedez benz that is 4 yr old with mileage 45000

In [70]:
lr.predict([[2,45000,4]])

array([[33336.7721827]])

# 2) Predict price of a BMW X5 that is 7 yr old with mileage 86000

In [71]:
lr.predict([[1,86000,7]])

array([[16106.74127344]])

# 3score (accuracy) of Linear  model. 

In [73]:
lr.score(x,y)

0.8719970367825953

In [74]:
import pickle

In [76]:
pickle.dump(lr,open('car price model encoded','wb'))

In [77]:
results=lr.predict(x)

In [79]:
results=pd.DataFrame(results)

In [88]:
results.rename({'0':'predicted Price'},axis='columns',inplace=True)

In [90]:
results.columns=['Predicted Price']

In [91]:
results

Predicted Price
0      22855.471767
1      36101.346909
2      27545.285691
3      40997.052489
4      31823.316300
5      25620.046493
6      28502.529693
7      20518.449256
8      13197.737981
9      24780.710965
10     18443.763785
11     20090.897042
12     27823.391631

In [95]:
results.to_csv("Predicated Price of cars.csv")